name: Deploy Multi-Server Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Europe Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /opt/multi-server-devops

            echo "Pulling latest code..."
            git pull origin main

            echo "Building Docker images..."
            docker compose build

            echo "Starting application..."
            docker compose up -d

            echo "Removing unused Docker images..."
            docker image prune -f

            echo "Deployment completed successfully."

            docker compose ps
